### PR TITLE
Update fixes

### PR DESCRIPTION
**Pull request by georgemarshall**

### CODE REVIEW

**Comment by jackson541** [comment]
Hello
I am just waiting to merge this PR to use the library! :smile:

**Comment by libcthorne** [comment]
@georgemarshall Great to see this merged 👍 Is it possible to push 1.1 to pypi? (https://pypi.org/project/django-cryptography/)

**Comment by georgemarshall** [comment]
> According to the action site, using the workflow is considered deprecated: https://github.com/pre-commit/action/blob/main/README.md?plain=1#L1

There is no compelling reason to switch

**Comment by georgemarshall** [comment]
> @georgemarshall Great to see this merged 👍 Is it possible to push 1.1 to pypi? (https://pypi.org/project/django-cryptography/)

Still sifting through tickets to ensure I have not missed anything important before cutting a release.

**Pull request merged**
